# Copyright (c) Soumyadip Sarkar.
# All rights reserved.
#
# This source code is licensed under the Apache-style license found in the
# LICENSE file in the root directory of this source tree.

"""`describe_api`, `search_api` and `help()` are shipped features, so the
descriptions they read have to exist.

They did not. 363 of 503 public symbols -- 72% -- had no docstring, so
`describe_api` fell back to printing the *type* of the object:

    >>> mt.describe_api("abs")
    - abs: builtin_function_or_method

which is an implementation detail dressed as documentation, and `help(mt.abs)`
showed nothing at all. The same gap hid the fact that a doc comment meant for
the `Optimizer` class had drifted onto a private helper function below it.

The test that matters here is `test_every_public_symbol_has_a_description`: it
fails on any new symbol added without one, which is the only thing that keeps
this from decaying straight back.
"""

from __future__ import annotations

import pytest

import minitensor as mt

# Whatever `describe_api` prints when it has nothing to say. These are the
# repr of a *type*, never a description of behaviour.
PLACEHOLDERS = {
    "builtin_function_or_method",
    "function",
    "method_descriptor",
    "type",
    "PyCapsule",
}


def _public_symbols():
    for module, names in mt.list_public_api().items():
        for name in names:
            yield (name if module == "top_level" else f"{module}.{name}")


def _description(symbol: str) -> str:
    return mt.describe_api(symbol).split(": ", 1)[-1].strip()


@pytest.mark.parametrize("symbol", sorted(_public_symbols()))
def test_every_public_symbol_has_a_description(symbol):
    description = _description(symbol)
    assert (
        description not in PLACEHOLDERS
    ), f"{symbol} has no docstring, so describe_api prints its type instead"
    assert not description.startswith("Python wrapper for"), (
        f"{symbol} describes itself by naming the Rust type it wraps, which "
        "tells a Python caller nothing"
    )
    assert len(description) > 12, f"{symbol}: {description!r} is too short to inform"


@pytest.mark.parametrize("symbol", sorted(_public_symbols()))
def test_descriptions_are_one_line(symbol):
    """`describe_api` and `help()` print one line per symbol, so a description
    whose first line trails off mid-sentence reads as truncated."""
    description = _description(symbol)
    assert "\n" not in description
    assert not description.endswith((",", "and", "or", "the", "a", "of"))


# The forwarders in `functional.rs` are generated by a macro that carries its
# own copy of each description, because the method it calls lives in a
# `#[pymethods]` block that the macro cannot reach. Two copies can drift, so
# they are compared rather than trusted.
FORWARDED = [
    "abs",
    "acos",
    "acosh",
    "asin",
    "asinh",
    "atan",
    "atanh",
    "bitwise_not",
    "ceil",
    "cos",
    "cosh",
    "erf",
    "erfc",
    "exp",
    "expm1",
    "floor",
    "log",
    "log10",
    "log1p",
    "log2",
    "reciprocal",
    "relu",
    "rsqrt",
    "selu",
    "sigmoid",
    "sign",
    "silu",
    "sin",
    "sinh",
    "softsign",
    "sqrt",
    "tan",
    "tanh",
    "eq",
    "ge",
    "gt",
    "le",
    "lt",
    "ne",
    "floor_divide",
    "remainder",
]


@pytest.mark.parametrize("name", FORWARDED)
def test_forwarders_and_methods_describe_themselves_identically(name):
    forwarder = getattr(mt, name).__doc__
    method = getattr(mt.Tensor, name).__doc__

    assert forwarder is not None, f"mt.{name} has no docstring"
    assert method is not None, f"Tensor.{name} has no docstring"
    assert (
        forwarder.strip() == method.strip()
    ), f"mt.{name} and Tensor.{name} describe the same operation differently"


def test_search_api_matches_names_not_descriptions():
    """Worth pinning: `search_api('normalize')` finding nothing is the
    documented behaviour, not a symptom of the missing descriptions above."""
    assert "top_level.softmax" in mt.search_api("softmax")
    assert mt.search_api("Normalize along") == []


def test_describe_api_rejects_an_unknown_symbol():
    with pytest.raises(ValueError) as excinfo:
        mt.describe_api("nn.Linear")
    assert "Unknown symbol" in str(excinfo.value)


def test_help_output_carries_the_descriptions():
    text = mt.help()
    assert "Element-wise absolute value." in text
    assert "builtin_function_or_method" not in text
